### ISSUE TITLE
Edge prediction models not working in edge prediction evaluation pipeline

### ISSUE THREAD

**Issue by DylanSteinecke** [AnacletoLAB/grape#34]
When using the edge prediction evaluation pipeline, I tried running a few different edge prediction models (e.g., KipfGCNEdgePrediction, not for the MLP, Decision Tree, or Random Forest), I got this error: 
 
Traceback (most recent call last):
  File [script I ran] 
\<module> KipfGCNEdgePrediction(),
  File "/home/dylansteinecke/anaconda3/lib/python3.9/site-packages/embiggen/utils/abstract_models/model_stub.py", line 101, in __init__
    super().__init__(**parent_class.smoke_test_parameters())
  File "/home/dylansteinecke/anaconda3/lib/python3.9/site-packages/embiggen/utils/abstract_models/abstract_model.py", line 124, in smoke_test_parameters
    raise NotImplementedError((
NotImplementedError: The `smoke_test_parameters` method must be implemented in the child classes of abstract model.

Is there a way I can address it or are these models not currently permitted in the edge prediction evaluation pipeline? Thank you.

**Comment by LucaCappelletti94** [comment]
I think that is an error caused by a combination of errors, do you have TensorFlow and sklearn installed? I am on discord if you want to do a quick call.
